version: '3.1'
services:
  football-api:
    build: .
    image: afatsini/football-api
    restart: always
    environment:
     - SERVICE_PORTS=4000
    networks:
       - web
    deploy:
     replicas: 3
     update_config:
       parallelism: 3
       delay: 10s
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
  proxy:
      image: dockercloud/haproxy
      depends_on:
        - football-api
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 80:80
      networks:
        - web
      deploy:
        placement:
          constraints:
            - node.role == manager

networks:
  web:
    driver: overlay
